### ISSUE TITLE
[Week1] 暖身周

### ISSUE THREAD

**Issue by prochini** [Lidemy/homeworks-3rd#15]
作業連結
https://github.com/Lidemy/mentor-program-3rd-prochini/tree/master/homeworks/week1

可以自己 merge pull request 所以就自己 merge 了，
想發問下次要停留 pull request 狀態還是已merge 並刪除 branch 的狀態?

**Comment by aszx87410** [comment]
應該要附這個連結XD
https://github.com/Lidemy/mentor-program-3rd-prochini/pull/1

然後 pull request 照理來說應該沒權限合併才對QQ 應該是我設定沒調好
下次發作業記得停在 pull request 狀態就好，不要 merge，我改完會 merge
