### ISSUE TITLE
[Week3] hw5

### ISSUE THREAD

**Issue by RZ-Huang** [Lidemy/homeworks-3rd#329]
https://github.com/Lidemy/mentor-program-3rd-RZ-Huang/pull/6
@aszx87410 

完成第三週的大數加法。

OJ 測試有過，但是不確定這種寫法是不是可以的，我有看了解答，寫得非常簡短，也沒有使用 `codePointAt()` 這個內建函式。

**Comment by aszx87410** [comment]
可以啊，基本上只要能過沒什麼不行的
但要把字串轉數字，用 `Number(str)` 或是 `parseInt(str, 10)` 都會更有可讀性一點，所以一般不會看到有人用 codePointAt 來轉
