### ISSUE TITLE
[Week1] Yakim

### ISSUE THREAD

**Issue by yakim-shu** [Lidemy/homeworks-3rd#38]
阿有個問題想問：

有辦法在不上 GitHub 網頁的情況下，知道遠端有檔案變動嗎？或是具體說有什麼指令可以查看嗎？
感謝～

( 剛剛發現問錯地方了哈哈哈哈，重問一次 )

**Comment by yakim-shu** [comment]
Lidemy/mentor-program-3rd-yakim-shu#1
啊忘記附上連結了抱歉

**Comment by aszx87410** [comment]
其實問在原本 PR 那邊就行了XD
作業寫得很好！幫你加上值得參考的標籤
